cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
    - 2.12.7

jdk:
    - openjdk8

branches:
  only:
    - master

script: 
    - sbt ++$TRAVIS_SCALA_VERSION clean compile test
